import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — MatchupLens",
  description: "Important disclaimers about predictions and betting content on MatchupLens.",
};

export default function DisclaimerPage() {
  return (
    <article>
      <h1 className="page-title">Disclaimer</h1>
      <p className="page-sub">Last updated: June 2026</p>

      <div className="panel" style={{ marginTop: 24, lineHeight: 1.8 }}>
        <div className="storyline" style={{ borderLeftColor: "var(--red)", marginBottom: 24 }}>
          <strong>Important:</strong> MatchupLens predictions are for entertainment purposes only
          and are not betting advice. Never wager more than you can afford to lose.
        </div>

        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>Predictions Are Not Guarantees</h2>
        <p style={{ marginBottom: 16 }}>
          All win probabilities, picks, and predictions shown on MatchupLens are generated by an
          automated statistical model using publicly available data including team records, betting
          market lines, and head-to-head history. These predictions are editorial analysis intended
          for entertainment and informational purposes only.
        </p>
        <p style={{ marginBottom: 16 }}>
          No prediction on this site guarantees any outcome. Sports are inherently unpredictable.
          Any model — no matter how sophisticated — can and will be wrong. Do not make financial
          decisions based on our predictions.
        </p>

        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>Betting and Gambling</h2>
        <p style={{ marginBottom: 16 }}>
          MatchupLens displays betting market information (lines, odds, over/unders) sourced from
          third-party data providers for informational context only. This information is not a
          solicitation to place any bet. Sports betting is only legal in certain jurisdictions.
          Know your local laws before placing any wager.
        </p>
        <p style={{ marginBottom: 16 }}>
          If you choose to bet, wager responsibly. Set limits. Never chase losses.
          Must be 21+ (18+ in some jurisdictions). Problem gambling resources:
          <strong> 1-800-GAMBLER</strong> (US) or visit{" "}
          <a href="https://www.ncpgambling.org" target="_blank" rel="noopener noreferrer" style={{ color: "var(--blue)" }}>
            ncpgambling.org
          </a>.
        </p>

        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>Data Accuracy</h2>
        <p style={{ marginBottom: 16 }}>
          Sports data is sourced from third-party APIs and updated approximately every 60 seconds.
          There may be delays, errors, or omissions. MatchupLens is not responsible for any
          inaccuracies in scores, stats, odds, or injury information.
        </p>

        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>No Affiliation with Leagues</h2>
        <p>
          MatchupLens is an independent website and is not affiliated with, endorsed by, or
          officially connected to the NBA, NFL, MLB, NHL, UFC, MLS, FIFA, or any other sports
          organization. Team names, logos, and trademarks are property of their respective owners.
        </p>
      </div>
    </article>
  );
}
